### ISSUE TITLE
it not working in node_modules?

### ISSUE THREAD

**Issue by wuzeru** [patrick-steele-idem/app-module-path-node#17] opened 2016-05-30 06:00 UTC
my app is working   in node_modules as  a module,but app-module-path seems to not working in node_module. it can not add path in module.paths

**Comment by nurbek-ab** [comment] 2016-05-31 08:14
This behavior is made by design and described in the documentation.

**Comment by patrick-steele-idem** [comment] 2016-05-31 15:22
@wuzeru as @nurbek-ab pointed out, this is by design. I feel it would be very problematic for installed modules to manipulate the module search path or to allow installed modules to import modules from a custom application-level module search path. If you have thoughts or concerns please share, but for now I will go ahead and close this issue.

**Closed by patrick-steele-idem** 2016-05-31 15:22 UTC
